"use client";
// import type { Metadata } from 'next'
import "./globals.css";
import NavBar from "@/components/NavBar";
import { ThemeProvider } from "next-themes";

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="dark:bg-background text-background dark:text-text">
        <ThemeProvider attribute={"class"}>
          <header>
            <NavBar />
          </header>
          <main className="@container/main xs:px-4">{children}</main>
        </ThemeProvider>
      </body>
    </html>
  );
}
